# sh prep_data.sh (1)dataset (2)year_as_test
date

# split by 2012
python split_data.py $1 $2

# gen feature
# past_data ans_data are generated by split_data.py
cp ./data/past_data ./data/sample_data
python gen_feature.py ./data/past_data ./data/ans_data ./data/sample_data ./data/feature_data 1

# gen test data feature
python gen_feature.py ../dataset/CN3.txt_no_repeat None ../dataset/CN3_query.txt ./data/feature_data_query -1

# merge 2 feature data and scale
cat ./data/feature_data_query >> ./data/feature_data
lib/libsvm/svm-scale -u 10 -l -10 ./data/feature_data > data/feature_data_scale

# separate files back
python separate_back.py ./data/feature_data_scale ./data/feature_data_scale_past ./data/feature_data_scale_query

# gen half data
python gen_half_data.py ./data/feature_data_scale_past ./data/feature_data_scale_past_half

date